version: '3.8'
services:
    postgres:
        image: postgres:10.5
        restart: always
        env_file:
          - ".env"
        logging:
          options:
            max-size: 10m
            max-file: "3"
        healthcheck:
              test: ["CMD-SHELL", "pg_isready -U postgres"]
              interval: "10s"
              timeout: "5s"
              retries: 5
        ports:
          - '5432:5432'
        volumes:
          - postgres:/var/lib/postgresql/data
          # Copy the sql script to create tables
          - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    shortlink:
        container_name: shortlink
        build: .
        env_file:
          - ".env"
        healthcheck:
          test: "curl localhost:5000/"
          interval: "10s"
          timeout: "3s"
          start_period: "2s"
          retries: 3
        ports:
          - "5000:5000"
        volumes:
          - .:/opt/
        depends_on:
          - postgres
        restart: unless-stopped
        stop_grace_period: 3s

volumes:
  postgres:
